{
 "title": "Drifts",
 "time": { "from": "2021-02-10T23:27:18.463Z", "to": "2021-02-11T08:16:36.725Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Token drift in days",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Days" }
   ],
   "targets": [
    { "expr": "token_drift_days", "legendFormat": "{{token}}" }
   ]
  },
  {
   "title": "Certificates drift in days",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Days" }
   ],
   "targets": [
    { "expr": "certificate_drift_days", "legendFormat": "{{certificate}}" }
   ]
  },
  {
   "title": "Token drift in seconds",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    { "expr": "token_drift_seconds", "legendFormat": "{{token}}" }
   ]
  },
  {
   "title": "Certificates drift in seconds",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    { "expr": "certificate_drift_seconds", "legendFormat": "{{certificate}}" }
   ]
  }
 ]
}